const words = [
    { category: 'Food', value: 'Sushi' },
    { category: 'Food', value: 'Milkshake' },
    { category: 'Food', value: 'Apple pie' },
    { category: 'Food', value: 'Fried Chicken' },
    { category: 'Food', value: 'Pancake' },
    { category: 'Food', value: 'Bacon' },
    { category: 'Food', value: 'Peanut' },
    { category: 'Food', value: 'Peach' },
    { category: 'Food', value: 'Ramen' },
    { category: 'Food', value: 'Hamburger' },
    { category: 'Sport', value: 'Football' },
    { category: 'Sport', value: 'Baseball' },
    { category: 'Sport', value: 'Basketball' },
    { category: 'Sport', value: 'Field hockey' },
    { category: 'Sport', value: 'Ice hockey' },
    { category: 'Sport', value: 'Figure skating' },
    { category: 'Brand', value: 'Apple' },
    { category: 'Brand', value: 'Amazon' },
    { category: 'Brand', value: 'Microsoft' },
    { category: 'Brand', value: 'Google' },
    { category: 'Brand', value: 'Samsung' },
    { category: 'Brand', value: 'Coca-Cola' },
    { category: 'Brand', value: 'Facebook' },
    { category: 'Brand', value: 'Disney' },
    { category: 'Brand', value: 'Nike' },
    { category: 'Emotion', value: 'Humble' },
    { category: 'Emotion', value: 'Active' },
    { category: 'Emotion', value: 'Assertive' },
    { category: 'Emotion', value: 'Friendly' },
    { category: 'Emotion', value: 'Diligent' },
    { category: 'Emotion', value: 'Reliable' },
    { category: 'Emotion', value: 'Organized' },
]

export default words
